sudo: required

services:
  - docker
  
before_install:
 - docker login --username=$U --password=$P --email=$E
 
script: 
 - docker build -t tyurikov/centos-java8 . 
 - docker push tyurikov/centos-java8
